# Lesson 2

How to customize reactions
```{r setup_lesson2, include=FALSE, cache=FALSE}
knitr::read_chunk("RScripts/L02_Script01_Example1.R")
knitr::read_chunk("RScripts/L02_Script02_Render.R")
knitr::read_chunk("RScripts/L02_Script03_Reactive.R")
knitr::read_chunk("RScripts/L02_Script04_Isolate.R")
knitr::read_chunk("RScripts/L02_Script05_observeEvent.R")
knitr::read_chunk("RScripts/L02_Script06_eventReactive.R")
knitr::read_chunk("RScripts/L02_Script07_reactiveValues.R")
knitr::read_chunk("RScripts/L02_Script08_PPQuestion01.R")
knitr::read_chunk("RScripts/L02_Script09_PPQuestion02.R")
knitr::read_chunk("RScripts/L02_Script10_PPSolution02.R")
knitr::read_chunk("RScripts/L02_Script11_PPQuestion03.R")
knitr::read_chunk("RScripts/L02_Script12_PPSolution03.R")
```

## Example #1
```{r,L02_Script01_Example1, eval=FALSE}

```


## render*()
```{r,L02_Script02_Render, eval=FALSE}

```

## reactive()
```{r,L02_Script03_Reactive, eval=FALSE}

```

## isolate()
```{r,L02_Script04_Isolate, eval=FALSE}

```

## observeEvent()
```{r,L02_Script05_observeEvent, eval=FALSE}

```

## eventReactive()
```{r, L02_Script06_eventReactive, eval=FALSE}

```

## reactiveValues()
```{r, L02_Script07_reactiveValues, eval=FALSE}

```

## Practice Problem #1
### Question
```{r, L02_Script08_PPQuestion01, eval=FALSE}

```


## Practice Problem #2
### Question
```{r, L02_Script09_PPQuestion02, eval=FALSE}

```

### Solution
```{r, L02_Script10_PPSolution02, eval=FALSE}

```

## Practice Problem #3
### Question
```{r, L02_Script11_PPQuestion03, eval=FALSE}

```

### Solution
```{r, L02_Script12_PPSolution03, eval=FALSE}

```